  #
  # ~/.zshrc
  #

  # Lines configured by zsh-newuser-install
  HISTFILE=~/.histfile
  HISTSIZE=1000
  SAVEHIST=1000
  bindkey -e
  # End of lines configured by zsh-newuser-install
  # The following lines were added by compinstall
  zstyle :compinstall filename '/home/arch/.zshrc'

  autoload -Uz compinit
  compinit
  # End of lines added by compinstall

  source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

  alias ls='ls --color=auto'
  PROMPT='%F{magenta}%n@%m%f:%F{blue}%~%f%B%(?.%F{green}.%F{red}) >%f%b '
  RPROMPT='%F{magenta}%T%f'
